name: Deploy GOAT.CORP to PROD

on:
  push:
    branches:
      - main

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      - name: Set Vercel Environment Variables
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          # Environment variables to set
          NEXT_PUBLIC_RETAIL_CRM_API: ${{ secrets.NEXT_PUBLIC_RETAIL_CRM_API }}
          NEXT_PUBLIC_CDEK_ACCOUNT_IDENTIFIER: ${{ secrets.NEXT_PUBLIC_CDEK_ACCOUNT_IDENTIFIER }}
          NEXT_PUBLIC_CDEK_SECRET: ${{ secrets.NEXT_PUBLIC_CDEK_SECRET }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}
          NEXT_PUBLIC_YANDEX_MAPS_SECRET: ${{ secrets.NEXT_PUBLIC_YANDEX_MAPS_SECRET }}
          NEXT_PUBLIC_YOOKASSA_TEST_KEY: ${{ secrets.NEXT_PUBLIC_YOOKASSA_TEST_KEY }}
          NEXT_PUBLIC_YOOKASSA_TEST_SHOP_ID: ${{ secrets.NEXT_PUBLIC_YOOKASSA_TEST_SHOP_ID }}
        run: |
          # Loop through each environment variable and set it in Vercel
          echo "Setting Vercel Environment Variables..."
          for var in NEXT_PUBLIC_RETAIL_CRM_API NEXT_PUBLIC_CDEK_ACCOUNT_IDENTIFIER NEXT_PUBLIC_CDEK_SECRET NEXT_PUBLIC_SITE_URL NEXT_PUBLIC_ENVIRONMENT NEXT_PUBLIC_YANDEX_MAPS_SECRET NEXT_PUBLIC_YOOKASSA_TEST_KEY NEXT_PUBLIC_YOOKASSA_TEST_SHOP_ID; do
            value=$(printenv $var)
            echo "Setting $var"
            vercel env add $var production --token $VERCEL_TOKEN <<EOF
            $value
            EOF
            done

      - name: Build Project Artifacts
        env:
          # Include build-time environment variables
          NEXT_PUBLIC_RETAIL_CRM_API: ${{ secrets.NEXT_PUBLIC_RETAIL_CRM_API }}
          NEXT_PUBLIC_CDEK_ACCOUNT_IDENTIFIER: ${{ secrets.NEXT_PUBLIC_CDEK_ACCOUNT_IDENTIFIER }}
          NEXT_PUBLIC_CDEK_SECRET: ${{ secrets.NEXT_PUBLIC_CDEK_SECRET }}
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          NEXT_PUBLIC_ENVIRONMENT: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT }}
          NEXT_PUBLIC_YANDEX_MAPS_SECRET: ${{ secrets.NEXT_PUBLIC_YANDEX_MAPS_SECRET }}
          NEXT_PUBLIC_YOOKASSA_TEST_KEY: ${{ secrets.NEXT_PUBLIC_YOOKASSA_TEST_KEY }}
          NEXT_PUBLIC_YOOKASSA_TEST_SHOP_ID: ${{ secrets.NEXT_PUBLIC_YOOKASSA_TEST_SHOP_ID }}
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
